export const userModel = {
  profile: [
    'userId',
    'nom',
    'ema',
    'pic',
    'prs',
    'cts',
    'pes',
    'cpf',
    'ins',
    'bir',
    'gen',
    'raz',
    'cnpj',
    'loc',
    'geo',
    'cep',
    'reg',
    'cpl',
    'tel',
    'cel',
    'skl',
    'ban',
    'age',
    'cta',
    'tct',
    'crb',
    'crn',
    'crs',
    'crv',
    'crh',
    'tav',
    'qav',
    'avl',
    'desc',
    'imgs',
    'lnks',
    'sti',
    'msg',
  ],
  gen: [
    {key: 'm', value: 'm', text: 'Masculino'},
    {key: 'f', value: 'f', text: 'Feminino'},
  ],
  tct: [
    {key: 'c', value: 'c', text: 'Conta corrente'},
    {key: 'p', value: 'p', text: 'Conta poupança'},
  ],
  evento: [
    'eventId',
    'userId',
    'nom',
    'ema',
    'cel',
    'tel',
    'pic',
    'tit',
    'des',
    'tip',
    'dat',
    'ini',
    'fim',
    'lim',
    'vrt',
    'pai',
    'loc',
    'uf',
    'cid',
    'bai',
    'rua',
    'nro',
    'cep',
    'cpl',
    'geo',
    'reg',
    'sta',
    'can',
    'tea',
    'tsk',
  ],
  skl: [
    {key: 'a', text: 'Auxiliar de cozinha'},
    {key: 'b', text: 'Barman/Barwoman'},
    {key: 'p', text: 'Bartender'},
    {key: 'd', text: 'Bombeiro civil'},
    {key: 'j', text: 'Chapa de carga/descarga'},
    {key: 'h', text: 'Churrasqueiro'},
    {key: 'c', text: 'Cozinheiro'},
    {key: 'k', text: 'Decorador'},
    {key: 'i', text: 'Fiscal de banheiro'},
    {key: 'g', text: 'Garçon/Garçonete'},
    {key: 'f', text: 'Auxiliar de limpeza'},
    {key: 'm', text: 'Manobrista'},
    {key: 'n', text: 'Montador de eventos'},
    {key: 'r', text: 'Recepcionista/Hostess'},
    {key: 'e', text: 'Recreador'},
    {key: 't', text: 'Repositor de estoque'},
    {key: 's', text: 'Segurança'},
    {key: 'o', text: 'Serviços gerais'},
  ],
  tipos: [
    {key: '1', text: 'Aniversário'},
    {key: '2', text: 'Aniversário Infantil'},
    {key: '3', text: 'Casamento'},
    {key: '4', text: 'Confraternização'},
    {key: '5', text: 'Churrasco'},
    {key: '6', text: 'Congresso'},
  ],
  banks: [
    {key: '', text: ''},
    {key: '001', text: 'Banco do Brasil'},
    {key: '237', text: 'Bradesco'},
    {key: '341', text: 'Itaú'},
    {key: '351', text: 'Santander'},
    {key: '104', text: 'Caixa Econômica'},
    {key: '260', text: 'Nubank'},
    {key: '290', text: 'Pagseguro'},
    {key: '748', text: 'Sicredi'},
    {key: '422', text: 'Safra'},
    {key: '041', text: 'Banrisul'},
    {key: '021', text: 'Banestes'},
    {key: '077', text: 'Inter'},
    {key: '070', text: 'BRB'},
    {key: '212', text: 'Original'},
    {key: '746', text: 'Modal'},
    {key: '136', text: 'Unicred'},
  ],
  banks1: [
    {key: '', text: ''},
    {key: '001', text: '001 - Banco do Brasil'},
    {key: '003', text: '003 - Banco da Amazônia'},
    {key: '004', text: '004 - Banco do Nordeste'},
    {key: '021', text: '021 - Banestes'},
    {key: '025', text: '025 - Banco Alfa'},
    {key: '027', text: '027 - Besc'},
    {key: '029', text: '029 - Banerj'},
    {key: '031', text: '031 - Banco Beg'},
    {key: '033', text: '033 - Banco Santander Banespa'},
    {key: '036', text: '036 - Banco Bem'},
    {key: '037', text: '037 - Banpará'},
    {key: '038', text: '038 - Banestado'},
    {key: '039', text: '039 - BEP'},
    {key: '040', text: '040 - Banco Cargill'},
    {key: '041', text: '041 - Banrisul'},
    {key: '044', text: '044 - BVA'},
    {key: '045', text: '045 - Banco Opportunity'},
    {key: '047', text: '047 - Banese'},
    {key: '062', text: '062 - Hipercard'},
    {key: '063', text: '063 - Ibibank'},
    {key: '065', text: '065 - Lemon Bank'},
    {key: '066', text: '066 - Banco Morgan Stanley Dean Witter'},
    {key: '069', text: '069 - BPN Brasil'},
    {key: '070', text: '070 - Banco de Brasília - BRB'},
    {key: '072', text: '072 - Banco Rural'},
    {key: '073', text: '073 - Banco Popular'},
    {key: '074', text: '074 - Banco J. Safra'},
    {key: '075', text: '075 - Banco CR2'},
    {key: '076', text: '076 - Banco KDB'},
    {key: '096', text: '096 - Banco BMF'},
    {key: '104', text: '104 - Caixa Econômica Federal'},
    {key: '107', text: '107 - Banco BBM'},
    {key: '116', text: '116 - Banco Único'},
    {key: '151', text: '151 - Nossa Caixa'},
    {key: '175', text: '175 - Banco Finasa'},
    {key: '184', text: '184 - Banco Itaú BBA'},
    {key: '204', text: '204 - American Express Bank'},
    {key: '208', text: '208 - Banco Pactual'},
    {key: '212', text: '212 - Banco Matone'},
    {key: '213', text: '213 - Banco Arbi'},
    {key: '214', text: '214 - Banco Dibens'},
    {key: '217', text: '217 - Banco Joh Deere'},
    {key: '218', text: '218 - Banco Bonsucesso'},
    {key: '222', text: '222 - Banco Calyon Brasil'},
    {key: '224', text: '224 - Banco Fibra'},
    {key: '225', text: '225 - Banco Brascan'},
    {key: '229', text: '229 - Banco Cruzeiro'},
    {key: '230', text: '230 - Unicard'},
    {key: '233', text: '233 - Banco GE Capital'},
    {key: '237', text: '237 - Bradesco'},
    {key: '241', text: '241 - Banco Clássico'},
    {key: '243', text: '243 - Banco Stock Máxima'},
    {key: '246', text: '246 - Banco ABC Brasil'},
    {key: '248', text: '248 - Banco Boavista Interatlântico'},
    {key: '249', text: '249 - Investcred Unibanco'},
    {key: '250', text: '250 - Banco Schahin'},
    {key: '252', text: '252 - Fininvest'},
    {key: '254', text: '254 - Paraná Banco'},
    {key: '263', text: '263 - Banco Cacique'},
    {key: '265', text: '265 - Banco Fator'},
    {key: '266', text: '266 - Banco Cédula'},
    {key: '300', text: '300 - Banco de la Nación Argentina'},
    {key: '318', text: '318 - Banco BMG'},
    {key: '320', text: '320 - Banco Industrial e Comercial'},
    {key: '356', text: '356 - ABN Amro Real'},
    {key: '341', text: '341 - Itau'},
    {key: '347', text: '347 - Sudameris'},
    {key: '351', text: '351 - Banco Santander'},
    {key: '353', text: '353 - Banco Santander Brasil'},
    {key: '366', text: '366 - Banco Societe Generale Brasil'},
    {key: '370', text: '370 - Banco WestLB'},
    {key: '376', text: '376 - JP Morgan'},
    {key: '389', text: '389 - Banco Mercantil do Brasil'},
    {key: '394', text: '394 - Banco Mercantil de CrÃ©dito'},
    {key: '399', text: '399 - HSBC'},
    {key: '409', text: '409 - Unibanco'},
    {key: '412', text: '412 - Banco Capital'},
    {key: '422', text: '422 - Banco Safra'},
    {key: '453', text: '453 - Banco Rural'},
    {key: '456', text: '456 - Banco Tokyo Mitsubishi UFJ'},
    {key: '464', text: '464 - Banco Sumitomo Mitsui Brasileiro'},
    {key: '477', text: '477 - Citibank'},
    {key: '479', text: '479 - Itaubank (antigo Bank Boston)'},
    {key: '487', text: '487 - Deutsche Bank'},
    {key: '488', text: '488 - Banco Morgan Guaranty'},
    {key: '492', text: '492 - Banco NMB Postbank'},
    {
      key: '494',
      text: '494 - Banco la República Oriental del Uruguay',
    },
    {key: '495', text: '495 - Banco La Provincia de Buenos Aires'},
    {key: '505', text: '505 - Banco Credit Suisse'},
    {key: '600', text: '600 - Banco Luso Brasileiro'},
    {key: '604', text: '604 - Banco Industrial'},
    {key: '610', text: '610 - Banco VR'},
    {key: '611', text: '611 - Banco Paulista'},
    {key: '612', text: '612 - Banco Guanabara'},
    {key: '613', text: '613 - Banco Pecunia'},
    {key: '623', text: '623 - Banco Panamericano'},
    {key: '626', text: '626 - Banco Ficsa'},
    {key: '630', text: '630 - Banco Intercap'},
    {key: '633', text: '633 - Banco Rendimento'},
    {key: '634', text: '634 - Banco Triângulo'},
    {key: '637', text: '637 - Banco Sofisa'},
    {key: '638', text: '638 - Banco Prosper'},
    {key: '643', text: '643 - Banco Pine'},
    {key: '652', text: '652 - Itaú Holding Financeira'},
    {key: '653', text: '653 - Banco Indusval'},
    {key: '654', text: '654 - Banco A.J. Renner'},
    {key: '655', text: '655 - Banco Votorantim'},
    {key: '707', text: '707 - Banco Daycoval'},
    {key: '719', text: '719 - Banif'},
    {key: '721', text: '721 - Banco Credibel'},
    {key: '734', text: '734 - Banco Gerdau'},
    {key: '735', text: '735 - Banco Pottencial'},
    {key: '738', text: '738 - Banco Morada'},
    {key: '739', text: '739 - Banco Galvão de Negócios'},
    {key: '749', text: '740 - Banco Barclays'},
    {key: '741', text: '741 - BRP'},
    {key: '743', text: '743 - Banco Semear'},
    {key: '745', text: '745 - Banco Citibank'},
    {key: '746', text: '746 - Banco Modal'},
    {key: '747', text: '747 - Banco Rabobank International'},
    {key: '748', text: '748 - Banco Cooperativo Sicredi'},
    {key: '749', text: '749 - Banco Simples'},
    {key: '751', text: '751 - Dresdner Bank'},
    {key: '752', text: '752 - BNP Paribas'},
    {key: '753', text: '753 - Banco Comercial Uruguai'},
    {key: '755', text: '755 - Banco Merrill Lynch'},
    {key: '756', text: '756 - Banco Cooperativo do Brasil'},
    {key: '757', text: '757 - KEB'},
  ],
};

export const skillName = skill => {
  const reg = userModel.skl.find(s => s.key === skill);
  return reg ? reg.text : '???';
};
